Acme\AuthBundle\Entity\ClientFormValidate:
    properties:
        fieldLogin:
          - Length: { min: 5, minMessage: "Слишком короткий логин!" }
          - Regex: { pattern: "/^[a-zA-Z]+$/u", message: "Только латинские буквы!" }
        fieldPass:
          - Length: { min: 5, minMessage: "Слишком короткий пароль!" }
          - Regex: { pattern: "/^[a-zA-Z0-9]+$/u", message: "Только латинские буквы и цифры!" }
        fieldEmail:
          - Email: { message: "Указана неверная почта!", checkMX: true }

#Acme\AuthBundle\Entity\AuthorFormValidate:
#    properties:
#        fieldMobileTel:
#          - Length: { min: 7, minMessage: "Слишком короткий номер!" }
#          - Regex: { pattern: "/^((8|\+7|\+375)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,14}$/", message: "Только цифры!" }



