Acme\SecureBundle\Entity\Client\ClientProfileFormValidate:
    properties:
        fieldMobilePhone:
          - Length: { min: 7, minMessage: "Слишком короткий номер!" }
          - Regex: { pattern: "/^((8|\+7|\+375)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,14}$/", message: "Некорректный номер!" }
        fieldStaticPhone:
          - Length: { min: 7, minMessage: "Слишком короткий номер!" }
          - Regex: { pattern: "/^((8|\+7|\+375)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,14}$/", message: "Некорректный номер!" }
        fieldIcq:
          - Length: { min: 6, minMessage: "Слишком короткий номер!" }
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
        fieldUsername:
          - Length: { min: 1, minMessage: "Слишком короткое имя!" }
          - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }
        fieldSurname:
          - Length: { min: 1, minMessage: "Слишком короткая фамилия!" }
          - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }
        fieldLastname:
          - Length: { min: 1, minMessage: "Слишком короткое отчество!" }
          - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }

Acme\SecureBundle\Entity\Client\CreateOrderFormValidate:
    properties:
        fieldTheme:
          - Length: { min: 4, minMessage: "Слишком короткое название темы!" }
          - Regex: { pattern: "/^[a-zA-Zа-яА-Я-+()\s+\d]+$/u", message: "Только русские буквы!" }
        fieldOriginality:
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
          - GreaterThan: { value: 0, message: "Процент не может быть меньше 0!" }
          - LessThan: { value: 101, message: "Процент не может быть больше 100!" }
        fieldCountSheet:
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
          - GreaterThan: { value: 0, message: "Количество страниц не может быть меньше 0!" }
          - LessThan: { value: 501, message: "Количество страниц не может быть больше 500!" }
        #fieldTask:
        #  - Length: { min: 6, minMessage: "Слишком короткое описание!" }
          #- Regex: { pattern: "/^[\d]+$/", message: "Введите корректное описание!" }
        #fieldDescribe:
        #  - Length: { min: 3, minMessage: "Слишком короткое название темы!" }
        #  - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }

Acme\SecureBundle\Entity\Author\BidFormValidate:
    properties:
        fieldSum:
          - Length: { min: 1, minMessage: "Слишком маленькая сумма!" }
          - Regex: { pattern: "/^[\d]+$/u", message: "Только цифры!" }
          - NotBlank: { message: "Введите сумму!" }
        fieldDay:
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
          #- NotBlank: { message: "Введите количество дней!" }
        #fieldComment:
        #  - Regex: { pattern: "/^[A-Za-zА-Яа-я\d]+$/", message: "Только цифрыи буквы!" }

Acme\SecureBundle\Entity\Author\CreatePsFormValidate:
    properties:
        fieldNum:
          - Length: { min: 6, minMessage: "Слишком мало цифр!" }
          - Regex: { pattern: "/^[\d]+$/u", message: "Только цифры!" }
          - NotBlank: { message: "Введите номер кошелька!" }
        #fieldType:
        #  - NotBlank: { message: "Введите номер кошелька!" }
