Acme\SecureBundle\Entity\ClientProfileFormValidate:
    properties:
        fieldMobilePhone:
          - Length: { min: 7, minMessage: "Слишком короткий номер!" }
          - Regex: { pattern: "/^((8|\+7|\+375)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,14}$/", message: "Некорректный номер!" }
        fieldStaticPhone:
          - Length: { min: 7, minMessage: "Слишком короткий номер!" }
          - Regex: { pattern: "/^((8|\+7|\+375)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,14}$/", message: "Некорректный номер!" }
        fieldIcq:
          - Length: { min: 6, minMessage: "Слишком короткий номер!" }
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
        fieldUsername:
          - Length: { min: 1, minMessage: "Слишком короткое имя!" }
          - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }
        fieldSurname:
          - Length: { min: 1, minMessage: "Слишком короткая фамилия!" }
          - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }
        fieldLastname:
          - Length: { min: 1, minMessage: "Слишком короткое отчество!" }
          - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }

Acme\SecureBundle\Entity\CreateOrderFormValidate:
    properties:
        fieldTheme:
          - Length: { min: 4, minMessage: "Слишком короткое название темы!" }
          - Regex: { pattern: "/^[а-яА-Я\s+]+$/u", message: "Только русские буквы!" }
        fieldOriginality:
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
        fieldCountSheet:
          - Regex: { pattern: "/^[\d]+$/", message: "Только цифры!" }
        #fieldTask:
        #  - Length: { min: 6, minMessage: "Слишком короткое описание!" }
          #- Regex: { pattern: "/^[\d]+$/", message: "Введите корректное описание!" }
        #fieldDescribe:
        #  - Length: { min: 3, minMessage: "Слишком короткое название темы!" }
        #  - Regex: { pattern: "/^[а-яА-Я]+$/u", message: "Только русские буквы!" }